// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TransactionProcessorACL.IntegrationTests.RedeemVoucher
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RedeemVoucher")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [NUnit.Framework.CategoryAttribute("base")]
    [NUnit.Framework.CategoryAttribute("shared")]
    public partial class RedeemVoucherFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "shared"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RedeemVoucher", "RedeemVoucher", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "RedeemVoucher.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
            global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                        "Role Name"});
            table37.AddRow(new string[] {
                        "Merchant"});
            table37.AddRow(new string[] {
                        "VoucherRedemption"});
#line 6
 await testRunner.GivenAsync("the following security roles exist", ((string)(null)), table37, "Given ");
#line hidden
            global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table38.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST Scope",
                        "A scope for Estate Managememt REST"});
            table38.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST  Scope",
                        "A scope for Transaction Processor REST"});
            table38.AddRow(new string[] {
                        "transactionProcessorACL",
                        "Transaction Processor ACL REST  Scope",
                        "A scope for Transaction Processor ACL REST"});
            table38.AddRow(new string[] {
                        "voucherManagement",
                        "Voucher Management REST  Scope",
                        "A scope for Voucher Management REST"});
#line 11
 await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table38, "Given ");
#line hidden
            global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table39.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST",
                        "Secret1",
                        "estateManagement",
                        "merchantId, estateId, role"});
            table39.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        ""});
            table39.AddRow(new string[] {
                        "transactionProcessorACL",
                        "Transaction Processor ACL REST",
                        "Secret1",
                        "transactionProcessorACL",
                        "merchantId, estateId, role, contractId"});
            table39.AddRow(new string[] {
                        "voucherManagement",
                        "Voucher Management REST",
                        "Secret1",
                        "voucherManagement",
                        ""});
#line 18
 await testRunner.GivenAsync("the following api resources exist", ((string)(null)), table39, "Given ");
#line hidden
            global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "Scopes",
                        "GrantTypes"});
            table40.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "estateManagement,transactionProcessor,transactionProcessorACL,voucherManagement",
                        "client_credentials"});
            table40.AddRow(new string[] {
                        "merchantClient",
                        "Merchant Client",
                        "Secret1",
                        "transactionProcessorACL",
                        "password"});
            table40.AddRow(new string[] {
                        "redemptionClient",
                        "Redemption Client",
                        "Secret1",
                        "transactionProcessorACL",
                        "password"});
#line 25
 await testRunner.GivenAsync("the following clients exist", ((string)(null)), table40, "Given ");
#line hidden
            global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table41.AddRow(new string[] {
                        "serviceClient"});
#line 31
 await testRunner.GivenAsync("I have a token to access the estate management and transaction processor acl reso" +
                    "urces", ((string)(null)), table41, "Given ");
#line hidden
            global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table42.AddRow(new string[] {
                        "Test Estate 1"});
            table42.AddRow(new string[] {
                        "Test Estate 2"});
#line 35
 await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table42, "Given ");
#line hidden
            global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                        "Email Address",
                        "Password",
                        "Given Name",
                        "Family Name",
                        "EstateName",
                        "Roles"});
            table43.AddRow(new string[] {
                        "redemptionuser@testredemption1.co.uk",
                        "123456",
                        "TestRedemption",
                        "User1",
                        "Test Estate 1",
                        "VoucherRedemption"});
            table43.AddRow(new string[] {
                        "redemptionuser@testredemption2.co.uk",
                        "123456",
                        "TestRedemption",
                        "User2",
                        "Test Estate 2",
                        "VoucherRedemption"});
#line 40
 await testRunner.GivenAsync("I have created the following security users for voucher redemption", ((string)(null)), table43, "Given ");
#line hidden
            global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table44.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "True",
                        "True"});
            table44.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher",
                        "True",
                        "True"});
#line 45
 await testRunner.GivenAsync("I have created the following operators", ((string)(null)), table44, "Given ");
#line hidden
            global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table45.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher"});
            table45.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher"});
#line 50
 await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table45, "And ");
#line hidden
            global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table46.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract"});
            table46.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher",
                        "Hospital 2 Contract"});
#line 55
 await testRunner.GivenAsync("I create a contract with the following values", ((string)(null)), table46, "Given ");
#line hidden
            global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value",
                        "ProductType"});
            table47.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract",
                        "10 KES",
                        "10 KES",
                        "",
                        "Voucher"});
            table47.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher",
                        "Hospital 2 Contract",
                        "10 KES",
                        "10 KES",
                        "",
                        "Voucher"});
#line 60
 await testRunner.WhenAsync("I create the following Products", ((string)(null)), table47, "When ");
#line hidden
            global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "Town",
                        "Region",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table48.AddRow(new string[] {
                        "Test Merchant 1",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
            table48.AddRow(new string[] {
                        "Test Merchant 2",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 2"});
#line 65
 await testRunner.GivenAsync("I create the following merchants", ((string)(null)), table48, "Given ");
#line hidden
            global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table49.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table49.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 2"});
#line 70
 await testRunner.GivenAsync("I have assigned the following  operator to the merchants", ((string)(null)), table49, "Given ");
#line hidden
            global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                        "DeviceIdentifier",
                        "MerchantName",
                        "EstateName"});
            table50.AddRow(new string[] {
                        "123456780",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table50.AddRow(new string[] {
                        "123456781",
                        "Test Merchant 2",
                        "Test Estate 2"});
#line 75
 await testRunner.GivenAsync("I have assigned the following devices to the merchants", ((string)(null)), table50, "Given ");
#line hidden
            global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "MerchantName",
                        "ContractDescription"});
            table51.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Hospital 1 Contract"});
            table51.AddRow(new string[] {
                        "Test Estate 2",
                        "Test Merchant 2",
                        "Hospital 2 Contract"});
#line 80
await testRunner.WhenAsync("I add the following contracts to the following merchants", ((string)(null)), table51, "When ");
#line hidden
            global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                        "Reference",
                        "Amount",
                        "DateTime",
                        "MerchantName",
                        "EstateName"});
            table52.AddRow(new string[] {
                        "Deposit1",
                        "20.00",
                        "Today",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table52.AddRow(new string[] {
                        "Deposit1",
                        "20.00",
                        "Today",
                        "Test Merchant 2",
                        "Test Estate 2"});
#line 85
 await testRunner.GivenAsync("I make the following manual merchant deposits", ((string)(null)), table52, "Given ");
#line hidden
            global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName",
                        "MerchantName"});
            table53.AddRow(new string[] {
                        "merchantuser@testmerchant1.co.uk",
                        "123456",
                        "TestMerchant",
                        "User1",
                        "Test Estate 1",
                        "Test Merchant 1"});
            table53.AddRow(new string[] {
                        "merchantuser@testmerchant2.co.uk",
                        "123456",
                        "TestMerchant",
                        "User2",
                        "Test Estate 2",
                        "Test Merchant 2"});
#line 90
 await testRunner.GivenAsync("I have created the following security users", ((string)(null)), table53, "Given ");
#line hidden
#line 95
 await testRunner.GivenAsync("I am logged in as \"merchantuser@testmerchant1.co.uk\" with password \"123456\" for M" +
                    "erchant \"Test Merchant 1\" for Estate \"Test Estate 1\" with client \"merchantClient" +
                    "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
            global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                        "DateTime",
                        "TransactionNumber",
                        "TransactionType",
                        "TransactionSource",
                        "MerchantName",
                        "DeviceIdentifier",
                        "EstateName",
                        "OperatorName",
                        "TransactionAmount",
                        "CustomerAccountNumber",
                        "CustomerEmailAddress",
                        "ContractDescription",
                        "ProductName",
                        "RecipientEmail",
                        "RecipientMobile",
                        "MessageType",
                        "AccountNumber",
                        "CustomerName"});
            table54.AddRow(new string[] {
                        "Today",
                        "1",
                        "Sale",
                        "1",
                        "Test Merchant 1",
                        "123456780",
                        "Test Estate 1",
                        "Voucher",
                        "10.00",
                        "",
                        "",
                        "Hospital 1 Contract",
                        "10 KES",
                        "test@recipient.co.uk",
                        "",
                        "",
                        "",
                        ""});
#line 97
 await testRunner.WhenAsync("I perform the following transactions", ((string)(null)), table54, "When ");
#line hidden
#line 101
 await testRunner.GivenAsync("I am logged in as \"merchantuser@testmerchant2.co.uk\" with password \"123456\" for M" +
                    "erchant \"Test Merchant 2\" for Estate \"Test Estate 2\" with client \"merchantClient" +
                    "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
            global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                        "DateTime",
                        "TransactionNumber",
                        "TransactionType",
                        "TransactionSource",
                        "MerchantName",
                        "DeviceIdentifier",
                        "EstateName",
                        "OperatorName",
                        "TransactionAmount",
                        "CustomerAccountNumber",
                        "CustomerEmailAddress",
                        "ContractDescription",
                        "ProductName",
                        "RecipientEmail",
                        "RecipientMobile",
                        "MessageType",
                        "AccountNumber",
                        "CustomerName"});
            table55.AddRow(new string[] {
                        "Today",
                        "2",
                        "Sale",
                        "1",
                        "Test Merchant 2",
                        "123456781",
                        "Test Estate 2",
                        "Voucher",
                        "10.00",
                        "",
                        "",
                        "Hospital 2 Contract",
                        "10 KES",
                        "test@recipient.co.uk",
                        "",
                        "",
                        "",
                        ""});
#line 103
 await testRunner.WhenAsync("I perform the following transactions", ((string)(null)), table55, "When ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Redeem Vouchers")]
        [NUnit.Framework.CategoryAttribute("PRTest")]
        public async System.Threading.Tasks.Task RedeemVouchers()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Redeem Vouchers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 108
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
#line 109
 await testRunner.GivenAsync("I am logged in as \"redemptionuser@testredemption1.co.uk\" with password \"123456\" f" +
                        "or Estate \"Test Estate 1\" with client \"redemptionClient\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
 await testRunner.WhenAsync("I redeem the voucher for Estate \'Test Estate 1\' and Merchant \'Test Merchant 1\' tr" +
                        "ansaction number 1 the voucher balance will be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
 await testRunner.GivenAsync("I am logged in as \"redemptionuser@testredemption2.co.uk\" with password \"123456\" f" +
                        "or Estate \"Test Estate 2\" with client \"redemptionClient\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
 await testRunner.WhenAsync("I redeem the voucher for Estate \'Test Estate 2\' and Merchant \'Test Merchant 2\' tr" +
                        "ansaction number 2 the voucher balance will be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
