name: Code Coverage

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  workflow_dispatch:

jobs:  
  build:
    name: "Code Coverage"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4    

    - name: Restore Nuget Packages
      run: dotnet restore TransactionProcessorACL.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build TransactionProcessorACL.sln --configuration Release
        
    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "TransactionProcessorACL.Tests/TransactionProcessorACL.Tests.csproj" --configuration Release --no-build --verbosity normal --coverage --coverage-output "coverage/TransactionProcessorACL.Tests.cobertura.xml" --coverage-output-format cobertura
        dotnet test "TransactionProcessorACL.BusinessLogic.Tests/TransactionProcessorACL.BusinessLogic.Tests.csproj" --configuration Release --no-build --verbosity normal --coverage --coverage-output "coverage/TransactionProcessorACL.BusinessLogic.Tests.cobertura.xml" --coverage-output-format cobertura

    - name: Upload merged coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./TestResults/coverage/TransactionProcessorACL.Tests.cobertura.xml,./TestResults/coverage/TransactionProcessorACL.BusinessLogic.Tests.cobertura.xml
